### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by Monduiz** [osmlab/ohauth#13]
Is this still the standard way for iD's API to provide a login function?
Popups are no longer the way forward. In my tests, most browsers block them. Safari doesn't even give the user a notification. Popups have been abused unceremoniously.

Is there a way to change this to how the Tasking manager handles authorization?

**Comment by tmcw** [comment]
ohauth is just the authentication logic: [osm-auth](https://github.com/osmlab/osm-auth) would be the home for this issue, and it has a 'singlepage' option for exactly this. It's opt-in, because transitioning away from a page can accidentally lose state and some phones didn't support it correctly. Luckily iD's authentication logic rarely matters because as an embed on OSM, it inherits the domain's cookie.

**Comment by Monduiz** [comment]
Tom, 

Thank you. I have opened an issue there. Have you seen an example on how to set the option of loading in a frame with osmauth.js?

Bjenk
